
/*

389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.*/

var findTheDifference = function (s, t) {

    s=s.split("").sort();
    t=t.split("").sort();
    
    for(let i=0;i<s.length||t.length;i++){
        
    if(s[i]!=t[i]){
        return t[i];
    }
}
};

